### ISSUE TITLE
Review all protos to ensure all required methods are available

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-server#13]
- [x] Review if `hopr-server` is able to do `openChannel` and `closeChannel` and the required Protos for it.

**Comment by nionis** [comment]
Reviewed both methods:

- `openChannel` will open channel and wait until the transaction is mined to resolve
- `closeChannel` will emit transaction but **not** wait for it to be mined

As discussed, ideally we want to return `tx hash` in both instances, this is something we want to address in the future.

**Comment by nionis** [comment]
@jjperezaguinaga should we also make `openChannel` resolve immediately (not wait for tx to be mined), changing this will require a change to our tests too, but it will keep the API more consistent, on the other hand, since we will be running on xdai I assume the mining time wont be long, thoughts?

**Comment by 0xjjpa** [comment]
No, let's keep it as it is. Even w/`closeChannel`, time would be between `10` and `20` seconds anyway.
